version: 2.1

orbs:
  windows: circleci/windows@1.0.0
jobs:
  test:
    description: Setup and run application tests
    executor:
      name: windows/default
    steps:
      - run:
          name: "Dotnet version"
          command: dotnet.exe --list-sdks
      - checkout
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "GoSpeak/Test/Tests.csproj" }}
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore GoSpeak/GoSpeak.sln
      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "GoSpeak/Test/Tests.csproj" }}
      - run:
          name: "Run Application Tests"
          command: dotnet.exe test GoSpeak/Test/Tests.csproj --filter Test=Unit -v n --results-directory:test_coverage --collect:"Code Coverage"
      - run:
          name: "Print Working Directory"
          command: pwd
      - store_artifacts:
          path: C:\Users\circleci\project\test_coverage
  build:
    description: Build application with Release configuration
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Build Application according to some given configuration"
          command: dotnet.exe build  GoSpeak/QuestionService/QuestionService.csproj --configuration Release
workflows:
  test_and_build:
    jobs:
      - test
      - build:
          requires:
            - test
